/**
 * models/Documentation.js
 * --------------------------------------------------------------------------
 * Mongoose schema representing a single chunk of ingested documentation text
 * along with its dense vector embedding, as produced by Gemini's
 * "text-embedding-004" model (768 dimensions).
 *
 * -----------------------------------------------------------------------
 * REQUIRED: Atlas Vector Search Index Definition
 * -----------------------------------------------------------------------
 * Before queryDocs() will work, you must create a Vector Search index on
 * this collection in Atlas (Atlas UI -> Database -> Search -> Create Index
 * -> "JSON Editor", or via the Atlas Admin API / Atlas CLI).
 *
 * Suggested index name: "vector_index"
 * Collection: "documentations" (Mongoose pluralizes "Documentation" -> this)
 *
 * Index definition JSON:
 * {
 *   "fields": [
 *     {
 *       "type": "vector",
 *       "path": "embedding",
 *       "numDimensions": 768,
 *       "similarity": "cosine"
 *     }
 *   ]
 * }
 *
 * "cosine" similarity is used here because Gemini embeddings are optimized
 * for cosine/dot-product comparison. This must match what $vectorSearch
 * expects at query time (see controllers/ragController.js).
 * --------------------------------------------------------------------------
 */

const mongoose = require('mongoose');

const DocumentationSchema = new mongoose.Schema(
  {
    // The raw text chunk of documentation (a slice of a larger markdown/text doc).
    // This is what gets returned as "context" to the LLM at query time.
    content: {
      type: String,
      required: [true, 'Documentation content is required.'],
      trim: true,
    },

    // The dense vector representation of `content`, generated by
    // Gemini's text-embedding-004 model. Always expected to be exactly
    // 768 floats long for this model.
    embedding: {
      type: [Number],
      required: [true, 'Embedding vector is required.'],
      validate: {
        validator: function (arr) {
          return Array.isArray(arr) && arr.length === 768;
        },
        message: 'Embedding must be an array of exactly 768 numbers (text-embedding-004 output size).',
      },
    },

    // Optional metadata — useful for traceability, filtering, and citing
    // sources back to the user in the final answer.
    sourceName: {
      type: String,
      default: 'untitled-source',
      trim: true,
    },

    // Sequential index of this chunk within its source document, useful for
    // reconstructing order or debugging chunking behavior.
    chunkIndex: {
      type: Number,
      default: 0,
    },
  },
  {
    timestamps: true, // adds createdAt / updatedAt automatically
  }
);

/**
 * NOTE: We deliberately do NOT define a standard Mongoose/MongoDB index on
 * `embedding` here (e.g. via schema.index()). Atlas Vector Search indexes
 * are a distinct index type managed at the Atlas Search layer, not through
 * the standard MongoDB index API — attempting to create them via
 * `createIndex` will not produce a usable vector index.
 */

module.exports = mongoose.model('Documentation', DocumentationSchema);
